name: Publish Namespaced Artifact

on:
  push:
    branches:
      - 'master'
      - 'one-page'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compute Input Hash
        id: hash
        run: |
          HASH=$(sha256sum flake.nix resume.tex cletter.tex | sha256sum | cut -d' ' -f1)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Check Existing Artifact Hash
        run: |
          BRANCH_SAFE=$(echo "${{ github.ref_name }}" | tr '/' '-')
          git clone --depth=1 --branch=gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} deploy
          
          # No artifact means build proceeds
          cd deploy/$BRANCH_SAFE || exit 0
          
          if [ -f input.hash ]; then
            EXISTING_HASH=$(cat input.hash)
            if [ "$EXISTING_HASH" = "${{ steps.hash.outputs.hash }}" ]; then
              echo "No input changes detected, skipping build."
              # Neutral exit code, marks job as skipped
              exit 78
            fi
          fi

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh

      - name: Build Artifact
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix --experimental-features 'nix-command flakes' build .#packages.x86_64-linux.default
          cp result/andrew_huie.pdf .

      - name: Deploy Namespaced Artifact
        run: |
          BRANCH_SAFE=$(echo "${{ github.ref_name }}" | tr '/' '-')

          git config --global user.email "buildbot@example.com"
          git config --global user.name "buildbot"

          cd deploy
          mkdir -p "$BRANCH_SAFE"
          rm -f "$BRANCH_SAFE/andrew_huie.pdf" "$BRANCH_SAFE/input.hash"
          
          cp ../andrew_huie.pdf "$BRANCH_SAFE/"
          echo "${{ steps.hash.outputs.hash }}" > "$BRANCH_SAFE/input.hash"

          git add "$BRANCH_SAFE/"
          git commit -m "Update $BRANCH_SAFE artifact"
          git push

